name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install general dependencies
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential clang cmake pkg-config python3 python3-pip \
          libgl1-mesa-dev libx11-dev libxi-dev git

    # Build and install Raylib from source
    - name: Build and install Raylib
      run: |
        git clone https://github.com/raysan5/raylib.git
        cd raylib
        mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS=ON ..
        make -j4
        sudo make install
        sudo ldconfig

    # Build project and pack assets
    - name: Build project and pack assets
      run: make clang assets

    # Upload executable and assets
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ce_engine-release
        path: |
          ./ce_engine
          ./data.tcf
